# Generated by Django 3.2.8 on 2022-07-14 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kakeibo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetcategory',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='摘要'),
        ),
        migrations.AddField(
            model_name='incomecategory',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='摘要'),
        ),
        migrations.AddField(
            model_name='paymentcategory',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='摘要'),
        ),
    ]
